import {
  faKitchenSet,
  faTrophy,
  faStore,
  faUtensils,
  faWineGlass,
  faSeedling,
  faIdBadge,
  faChalkboard,
  faHandshake,
  faBowlFood,
  faEarthAfrica,
  faGavel,
  faUserTie,
  faCalendarDays,
  faClock,
  faLocationDot,
  faEnvelope,
  faPhone,
  faBars,
  faXmark,
  faChevronDown,
  faChevronRight,
  faChevronLeft,
  faArrowRight,
  faArrowUp,
  faExpand,
  faCircleCheck,
  faMagnifyingGlass,
  faImages,
  faCamera,
  faBuilding,
  faPaperPlane,
  faCreditCard,
  faLock,
  faCheck,
  faUsers,
  faStar,
  faPlay,
  faFilter,
  faQuoteLeft,
  faDownload,
  faGlobe,
  faTicket,
  faMedal,
  faMartiniGlassCitrus,
} from "@fortawesome/free-solid-svg-icons";
import {
  faFacebookF,
  faInstagram,
  faXTwitter,
  faLinkedinIn,
  faYoutube,
  faWhatsapp,
} from "@fortawesome/free-brands-svg-icons";

export const icons = {
  kitchen: faKitchenSet,
  trophy: faTrophy,
  medal: faMedal,
  store: faStore,
  utensils: faUtensils,
  bowlFood: faBowlFood,
  wineGlass: faWineGlass,
  cocktail: faMartiniGlassCitrus,
  seedling: faSeedling,
  idBadge: faIdBadge,
  chalkboard: faChalkboard,
  handshake: faHandshake,
  earthAfrica: faEarthAfrica,
  gavel: faGavel,
  userTie: faUserTie,
  calendar: faCalendarDays,
  clock: faClock,
  location: faLocationDot,
  envelope: faEnvelope,
  phone: faPhone,
  bars: faBars,
  close: faXmark,
  chevronDown: faChevronDown,
  chevronRight: faChevronRight,
  chevronLeft: faChevronLeft,
  arrowRight: faArrowRight,
  arrowUp: faArrowUp,
  expand: faExpand,
  check: faCircleCheck,
  checkPlain: faCheck,
  search: faMagnifyingGlass,
  images: faImages,
  camera: faCamera,
  building: faBuilding,
  send: faPaperPlane,
  card: faCreditCard,
  lock: faLock,
  users: faUsers,
  star: faStar,
  play: faPlay,
  filter: faFilter,
  quote: faQuoteLeft,
  download: faDownload,
  globe: faGlobe,
  ticket: faTicket,
  facebook: faFacebookF,
  instagram: faInstagram,
  x: faXTwitter,
  linkedin: faLinkedinIn,
  youtube: faYoutube,
  whatsapp: faWhatsapp,
} as const;

export type IconKey =
  | "chef-hat"
  | "trophy"
  | "store"
  | "utensils"
  | "wine-glass"
  | "seedling"
  | "id-badge"
  | "chalkboard"
  | "handshake";

export const dataIconMap: Record<IconKey, typeof icons.trophy> = {
  "chef-hat": icons.kitchen,
  trophy: icons.trophy,
  store: icons.store,
  utensils: icons.utensils,
  "wine-glass": icons.wineGlass,
  seedling: icons.seedling,
  "id-badge": icons.idBadge,
  chalkboard: icons.chalkboard,
  handshake: icons.handshake,
};
