export const paths = {
  home: "/",
  about: "/about-us",
  gastronomy: "/african-gastronomy",
  chefs: "/chefs-speakers",
  programmes: "/programmes-competitions",
  gallery: "/gallery",
  partners: "/partners-sponsors",
  countries: "/participating-countries",
  calendar: "/event-calendar",
  dashboard: "/dashboard",
  contact: "/contact",
  register: "/register",
  registerDetails: "/register/details",
  registerCategory: "/register/category",
  registerSummary: "/register/summary",
  registerPayment: "/register/payment",
  registerConfirmation: "/register/confirmation",
} as const;
